### ISSUE TITLE
Thumbnail image with items

### ISSUE THREAD

**Issue by theimpulson** [Themimitoof/genshin-feed#14]
Thanks a lot for this feed! I am wondering if it will be possible for you to add thumbnails from the official posts.

**Comment by Themimitoof** [comment]
Hello @theimpulson thanks for reaching me!

Just made an update server-side, thumbnails are back in all feeds!

![image](https://github.com/Themimitoof/genshin-feed/assets/1113348/b7e8b414-1e90-4ffd-9d06-5c54f2487bc6)
![image](https://github.com/Themimitoof/genshin-feed/assets/1113348/1924f44c-c9f1-4f63-9237-867081096519)
